/*jshint asi:true, nodejs:true, laxbreak:true*/

// FIXME: Make the location setting file work when you don't have write access to this app
exports.clientjs = __dirname + '/../Resources/index.js'
exports.bin = __dirname + '/apache-callback-mac'

var fs = require('fs')
var spawn = require('child_process').spawn

exports.start = function(url, onExit){
    
    // Set the URL before launching the app so it knows where to go
    var clientjs = '/* generated by ' + __filename + ' */\n'
    clientjs += 'location.replace(' + JSON.stringify(url) + ')'
    
    fs.writeFile(this.clientjs, clientjs, start)
    
    function start(){
        spawn(exports.bin)
        .on('exit', stop)
    }
    
    function stop(){
        // fs.writeFile(this.clientjs, '') // FIXME: remove this file instead
        onExit()
    }
}
