load("@prelude//apple:apple_bundle_impl.bzl", "apple_bundle")  # Load the rule directly
load("@prelude//apple:apple_library.bzl", "apple_library")
load("@prelude//apple:apple_resource.bzl", "apple_resource")


apple_library(
    name = "Appify_UI_23",
    srcs = ["Appify-UI-23/ContentView.swift", "Appify-UI-23/Appify_UI_23App.swift"],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/WebKit.framework",
        "$SDKROOT/System/Library/Frameworks/SwiftUI.framework",
    ],
    modular = True,  # Enable module support
)

apple_resource(
    name = "Appify_UI_23_Resources",
    dirs = [
        "Appify-UI-23/Assets.xcassets",
        "Appify-UI-23/Preview Content/Preview Assets.xcassets",
    ],
)

apple_bundle(  # Use the rule, not the macro
    name = "Appify-UI-23",
    binary = ":Appify_UI_23", 
    extension = "app",
    info_plist = "Appify-UI-23-Info.plist",
    entitlements_file = "Appify-UI-23/Appify_UI_23.entitlements",
    deps = [":Appify_UI_23_Resources"],
    default_target_platform = "toolchains//:apple", # add toolchain
)
